"use strict";

/**
 * This is an `ngconstant` autogenerated file.
 * To change values update the appropiate file in settings folder.
 */

angular.module("settings", [])

.constant("settings", {
  "auth": {
    "timeout": 25000
  },
  "chant": {
    "duration": 5000
  },
  "spinner": {
    "lines": "7",
    "length": "0",
    "width": "6",
    "radius": "8",
    "corners": "1",
    "rotate": "0",
    "direction": "1",
    "color": "#fff",
    "speed": "1.5",
    "trail": "52",
    "shadow": "false",
    "hwaccel": "true",
    "className": "spinner",
    "zIndex": "2e9",
    "top": "0%",
    "left": "0%"
  },
  "ENV": {
    "name": "development"
  },
  "facebook": {
    "appID": "352723474894646"
  },
  "apiEndpoint": {
    "url": "http://localhost:8000"
  },
  "wsService": {
    "url": "http://localhost:9999/ws",
    "pingUmbral": 10,
    "queryFrequency": 10000
  }
})

;